version: '3.9'

services:
  web:
    image: juanchogonza98/csm_dockerizado:latest
    container_name: csm_web
    environment:
      DJANGO_SETTINGS_MODULE: project.settings
      DATABASE_URL: postgres://postgres:postgres@db:5432/proyecto
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "
      python manage.py collectstatic --noinput &&
      python manage.py migrate --noinput &&
      python manage.py runserver 0.0.0.0:8000
      "

  db:
    image: postgres:16
    container_name: csm_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: proyecto
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
